const HTTP_STATUS_BAD_REQUEST = 400;
const HTTP_STATUS_CONFLICT = 409;
const HTTP_STATUS_NOT_FOUND = 404;
const HTTP_STATUS_CREATED = 201;
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
const MESSAGE_ERROR_NOT_VALID = 'Данные не валидны';
const MESSAGE_ERROR_CAST = 'Некорректный ID карточки';
const MESSAGE_ERROR_SERVER = 'Ошибка сервера';
const MESSAGE_ERROR_CARD_NOT_FOUND = 'Карточка с указанным ID не найдена';

module.exports = {

  HTTP_STATUS_BAD_REQUEST,
  HTTP_STATUS_CONFLICT,
  HTTP_STATUS_CREATED,
  HTTP_STATUS_NOT_FOUND,
  HTTP_STATUS_INTERNAL_SERVER_ERROR,
  MESSAGE_ERROR_NOT_VALID,
  MESSAGE_ERROR_CAST,
  MESSAGE_ERROR_SERVER,
  MESSAGE_ERROR_CARD_NOT_FOUND,
};
